sudo: required
dist: trusty

language: node_js
node_js: 10

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=stable
  - HAXE_VERSION=latest
  
install:
  - yarn global add lix
  - yarn
  - lix install haxe $HAXE_VERSION
  - lix download
  
script:
  - lix run travix node